Vagrant.configure("2") do |config|
  # Specify the base box
  config.vm.box = "bento/ubuntu-20.04"

  # VirtualBox specific configuration
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
  end

  # Synced folder configuration
  config.vm.synced_folder "/Users/milanakoval/Desktop", "/home/vagrant/lab5_cross"

  # Network port forwarding
  config.vm.network "forwarded_port", guest: 5145, host: 5145

  # Provisioning scripts
  config.vm.provision "shell", inline: <<-SHELL
    # Update and install necessary packages
    sudo apt-get update
    sudo apt-get install -y docker.io
    sudo systemctl start docker

    # Install the .NET SDK 8.0 from Microsoft feed
    wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
    sudo dpkg -i packages-microsoft-prod.deb
    sudo apt-get update
    sudo apt-get install -y dotnet-sdk-8.0

    # Pull the .NET Docker image
    sudo docker pull mcr.microsoft.com/dotnet/sdk:8.0
  SHELL
end
